### ISSUE TITLE
Evaluate moving to RethinkDB before going into production

### ISSUE THREAD

**Issue by aschmoe** [GovReady/GovReady-CMS-API#41]
Was recently reading about how unreliable Mongo can be, thus not ideal for production (example: https://engineering.meteor.com/mongodb-queries-dont-always-return-all-matching-documents-654b6594a827#.6y2gbsgwy)

Wonder if moving to RethinkDB might be a good move before we venture into production.

**Comment by aschmoe** [comment]
@jlyon @gregelin

**Comment by jlyon** [comment]
It looks like it would require quite a bit of refactoring. I feel like unless it's going to give us a big win with some of the security issues we're facing, we just want to get this into people's hands as quickly as possible, and that's probably going to be with a hosted, monitored Mongo instance (mLab).  Most of the realtime features of RethinkDB we're not going to need.

**Comment by aschmoe** [comment]
Yeah was more thinking about reliability at scale, but seems like that an issue to tackle down the road.  Closing for now.
