### ISSUE TITLE
Calls to /sites/5751ef431a13300335ea0b33/measures&method=GET

### ISSUE THREAD

**Issue by aschmoe** [GovReady/GovReady-CMS-API#42]
Seem to be either deleting siteId from measues (thus rendering them un-locatable), or deleting measures

**Comment by aschmoe** [comment]
@jlyon

**Comment by aschmoe** [comment]
@jlyon not as dramatic as all that turns out

https://github.com/GovReady/GovReady-CMS-API/blob/master/controllers/measureController.js#L25

Is calling a measureId param that doesn't exist

**Comment by jlyon** [comment]
My bad. Fixed, pushed and pulled.

**Comment by gregelin** [comment]
Can this item be closed?
