### ISSUE TITLE
Create new GovReady-Agent-Client repo

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-CMS-API#56]
@gregelin We would like to create a new repo "GovReady-Agent-Client"that will hold the source code for the client library that is used in the Drupal module, WP plugin, and GovReady-Q integration.  Could you temporarily give me admin rights to the GovReady Github organization so I can change the ownership on https://github.com/proudcity/GovReady-Agent-Client, or can you just create a new repo and give jlyon and aschmoe access? Thanks!

cc @aschmoe

**Comment by jlyon** [comment]
@gregelin Could we set up https://github.com/govready/GovReady-Agent-Client when you get a chance?

**Comment by gregelin** [comment]
Done. https://github.com/GovReady/GovReady-Agent-Client

**Comment by jlyon** [comment]
@gregelin One last thing here:  could you add GovReady/GovReady-Agent-Client  as a repo on https://waffle.io/GovReady/GovReady-WordPress-Agent/settings/sources?

Thanks!

**Comment by gregelin** [comment]
@jlyon I think I just did it.
