### ISSUE TITLE
Renew Let's Encrypt certificate on plugin.govready.com

### ISSUE THREAD

**Issue by gregelin** [GovReady/GovReady-CMS-API#66]
What do I need to do to renew the SSL Cert for plugin.govready.com? Will it renew automatically?

![screen shot 2017-04-17 at 10 35 16 pm](https://cloud.githubusercontent.com/assets/24979/25112272/2e20efc4-23be-11e7-90da-c1f1aedc8981.png)

**Comment by jlyon** [comment]
@gregelin I set up the `opts.renewWithin` param in express-letsencrypt so it autorenews 14 days before the ssl cert expires.  The ssl cert is now valid until July:
<img width="942" alt="screen shot 2017-04-18 at 9 45 44 pm" src="https://cloud.githubusercontent.com/assets/550909/25163643/b56aa822-2480-11e7-97dd-b006fab57ab4.png">

```
opts.renewWithin is the maximum number of days (in ms) before expiration to renew a certificate.
```
https://www.npmjs.com/package/letsencrypt-express

**Comment by gregelin** [comment]
Great! Thanks!
